### ISSUE TITLE
Sorry for this issue

### ISSUE THREAD

**Issue by MysteryPancake** [PatrickRatzow/EnhancedAvatarImage#1]
I'm sorry for this issue. I wrote it at a time when I was young and arrogant. I'm genuinely sorry for being so rude.

**Comment by patrickratzow** [comment]
You never submitted any pull requests? You forked this and commited to your fork, that's not my bad.
![kek](https://vgy.me/06KtBj.png)

**Comment by Mysterypancake1** [comment]
i'm dumber than I thought
